platform :ios, '9.0'
use_frameworks!

target 'iOSDCJP2016' do
  pod 'APIKit', '~> 2.0'
  pod 'Unbox', '~> 1.7'
  pod 'Alamofire', '~> 3.4'
  pod 'AlamofireImage', '~> 2.4'
#  pod 'UrbanAirship-iOS-SDK', '~> 7.2'
  pod 'URLNavigator', '~> 0.6'
  pod 'AcknowList'
  pod 'SVProgressHUD'
end

